* History of Lambda Calculus

The history culminating at the invention of Lambda Calculus is a bundle of braids that intertwine with each other to finally form the theoretical framework. The links could be traced back at least back until Aristotle and scholastic logic. But that would be a long winded way to open up the subject to an interested reader.

One good point I think is to start right after the logistic bent of history of logic, post the publication of Whitehead and Russell’s landmark Principia Mathematica which inspired Schönfinkel, Post, Turing, Church, and Gödel to come up with their theories of computation. In Principia Mathematica, which was influenced by Hilbert’s problems and with the thrust of the Fregean notational revolution, Russell and Whitehead attempted to formalize all of mathematics with the undergirding of logic. This is the project from which Church got inspired to create his Lambda Calculus.

* Completed

** [[https://amzn.to/2Lxak0t][Engines of Logic]]
Martin Davis (2000)

A good book by Martin Davis on the development that lead to mechanization of logic.

** [[https://pron.github.io/posts/computation-logic-algebra-pt1][Finite of Sense and Infinite of Thought: A History of Computation, Logic and Algebra]]
Ron Pressler (2018)

A detailed review by Ron Pressler on the historical incidents that generated the idea of computation.

* Survey/Overview

** [[https://dl.acm.org/doi/10.5555/57249.57252][Confluence of Ideas in 1936 ]]
Robin Gandy (October 1988)

** [[https://pdfs.semanticscholar.org/959d/32cfa6df9299312ba51e2102045e1f25bc18.pdf][History of Lambda Calculus and Combinatory Logic]]
Felice Cardone, Roger Hindley (2006)

** [[https://ieeexplore.ieee.org/document/4640786][Highlights of the History of the Lambda-Calculus]]
J. Barkley Rosser, 1984

** [[https://turing100.acm.org/lambda_calculus_timeline.pdf][Lambda Calculus Then and Now]]
Dana Scott (2012)
ACM Centenary Talk

** [[http://www.people.cs.uchicago.edu/~soare/History/handbook.pdf][The History and Concept of Computability]]
Robert I. Soare

** [[https://f.hypotheses.org/wp-content/blogs.dir/4029/files/2018/11/Hammache_SlidesBertinoro_compact.pdf][Lambda Calculus: From logic to computation]]
Wendy Hammache, 2018

** [[https://www.cs.helsinki.fi/u/jllang/Introduction_to_Lambda_Calculus_2020-02-20.pdf][Introduction to Lambda Calculus]]
John Lång, 2020

A great set of slides that explores the broad setting in which Lambda Calculus is situated.

* To Read

** Lambda calculus and combinators in the 20th century.
Cardone, Felice & J. Roger Hindley. 2009. 

** [[http://people.uleth.ca/~jonathan.seldin/CCL.pdf][The Logic of Church and Curry]]

Seldin, Jonathan P. 2009. 

** The impact of the lambda calculus in logic and computer science.
The Bulletin of Symbolic Logic 3.2: 181–215. DOI 10.2307/421013.

** Lambda Calculus Timeline (2010)
*Author: Dana Scott*

Download: https://turing100.acm.org/lambda_calculus_timeline.pdf

** The History and Concept of Computability
http://www.people.cs.uchicago.edu/~soare/History/handbook.pdf

** The Theory of Recursive Functions, approaching its centennial
https://projecteuclid.org/euclid.bams/1183548220

* Individual Subjects

** [[http://logicae.usal.es/mambo/index.php?option=com_summalogicaexxi&menu_task=Download&task=no_task&cmd=no_cmd&file_id=97][Alonzo Church: His Life, His Work, and Some of His Miracles (1996)]]
María Manzano

** [[https://link.springer.com/chapter/10.1007/978-3-319-22156-4_1][Conceptual Confluence in 1936]]
Post and Turing, Martin Davis and Wilfried Sieg (2015)

** [[http://people.uleth.ca/~jonathan.seldin/CCL.pdf][The Logic of Curry and Church]]
Peter Seldin, March 3 2008

* Tangential but interesting

** [[https://johnmacfarlane.net/church.html][Collection of Journal of Symbolic Logic reviews by Alonzo Church]]

** [[http://www.people.cs.uchicago.edu/~soare/History/handbook.pdf][History of Computability]]
Robert I. Soare

* People
Notes on the People who have contributed to Lambda Calculus

** Immediate Predecessors

- Frege
- Hilbert
- Ackermann
- Russell
- Moses Schönfinkel
- Alonzo Church
- Alan Turing
- Kurt Gödel
- Emil Post
- Stephen Kleene
- Haskell Curry
- Barker
- Dana Scott
- Christopher Strachey
- Peter Landin
- John Reynolds
- Gordon Plotkin
- Bagrendt
- D.A. Turner
- Story

** Precedents

*** 1800s
- Charles Babbage
- Jevons
- Venn

* Finished

** [[http://www-history.mcs.st-andrews.ac.uk/history/Extras/Rota_Church.html][Gian Carlo Rota on Church]]

*Author: Gian Carlo Rota*

Funny take on Church as a teacher. I might take up reading his book
Indiscrete Thoughts:
https://www.goodreads.com/book/show/1646354.Indiscrete_Thoughts to get
a better perspective of how things evolved during 1950-1990.

** [[https://www.tandfonline.com/doi/abs/10.1080/01445349708837290][Alonzo Church: His Life, His Work and Some of His Miracles]]
*Author: María Manzano*

Gives a detail of the background in which Lambda Calculus emerged. The
author attempts to portray Lambda Calculus as the great discovery of
Church and rest of his works as derivatives of that keystone work. It
also contains anecdotes from contemporaries and people who have worked
on the lineage of Lambda Calculus.

** [[https://homepages.inf.ed.ac.uk/wadler/papers/leicester/leicester-turing.pdf][Slide Deck on the evolution of Lambda Calculus by Philip Wadler]]
*Author: Philip Wadler*

A breezy overview of the evolution of Lambda Calculus. Shows links
with Gentzen's work.

** Highlights of the History of the  Lambda Calculus
https://ieeexplore.ieee.org/document/4640786

** Origins of recursive function theory (1981)
*Author: Stephen Cole Kleene*
https://www.computer.org/csdl/magazine/an/1981/01/man1981010052/13rRUNvyamS
