* History

* Finished

** [[http://www-history.mcs.st-andrews.ac.uk/history/Extras/Rota_Church.html][Gian Carlo Rota on Church]]

*Author: Gian Carlo Rota*

Funny take on Church as a teacher. I might take up reading his book
Indiscrete Thoughts:
https://www.goodreads.com/book/show/1646354.Indiscrete_Thoughts to get
a better perspective of how things evolved during 1950-1990.

** [[https://www.tandfonline.com/doi/abs/10.1080/01445349708837290][Alonzo Church: His Life, His Work and Some of His Miracles]]
*Author: María Manzano*


Gives a detail of the background in which Lambda Calculus emerged. The
author attempts to portray Lambda Calculus as the great discovery of
Church and rest of his works as derivatives of that keystone work. It
also contains anecdotes from contemporaries and people who have worked
on the lineage of Lambda Calculus.

** [[https://homepages.inf.ed.ac.uk/wadler/papers/leicester/leicester-turing.pdf][Slide Deck on the evolution of Lambda Calculus by Philip Wadler]]
*Author: Philip Wadler*

A breezy overview of the evolution of Lambda Calculus. Showed link
with Gentzen's work.


* To Read

** Lambda calculus and combinators in the 20th century.
Cardone, Felice & J. Roger Hindley. 2009. 

** The logic of Church and Curry.
Seldin, Jonathan P. 2009. 

** The impact of the lambda calculus in logic and computer science.
The Bulletin of Symbolic Logic 3.2: 181–215. DOI 10.2307/421013.

** Highlights of the History of the  Lambda Calculus
https://ieeexplore.ieee.org/document/4640786

** Origins of recursive function theory (1981)
*Author: Stephen Cole Kleene*
https://www.computer.org/csdl/magazine/an/1981/01/man1981010052/13rRUNvyamS

** Lambda Calculus Timeline (2010)
*Author: Dana Scott*

Download: https://turing100.acm.org/lambda_calculus_timeline.pdf

** The History and Concept of Computability
http://www.people.cs.uchicago.edu/~soare/History/handbook.pdf

** The Theory of Recursive Functions, approaching its centennial
https://projecteuclid.org/euclid.bams/1183548220
